CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
#BROKER_CONNECTION_RETRY_ON_STARTUP = False
CELERY_TASK_SERIALIZER = 'json'
#CELERY_ACCEPT_CONTENT = ['json']
